name: filters in github action
on:
    push:
        branches: 
            - main
            - '!feature'
    pull_request:
       types:
        - opened
        - closed
       paths-ignore:
            - 'README.md'
       branches:
        - main


jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
        - run: echo worksflow ---- ${{ github.event_name }}


